### ISSUE TITLE
Put your coments/bugs and reqests for enhancements here

### ISSUE THREAD

**Issue by lachlanA** [lachlanA/eagle-to-kicad#1]
Put your coments/bugs and reqests for enhancements here

**Comment by Wikiwide** [comment]
What about Eagle 7.4.0? And, is there a project for kicad-to-eagle?

Thank you. Best wishes.

**Comment by lachlanA** [comment]
Conversion from eagle libs to KiCad lib's should work, under Eagle 7.4, I have test it, and there is
no limit,  on how big the libs can be,  using the free version of Eagle 7.4,    as for the SCH
that should work too, but I have not test it,   While the PCB part,  where KiCad PCBNEW import's the Ealge XML PCB directly,  Mostly likely not, KiCad subports 6.xx of the PCB file's,   You can give it a try and give me a report.
There is a major update cumming for KiCad,   and after that,   there may be a chance that KiCad will
be updated to import version 7.4 of eagle PCB's, but for   now...  LIBS yes..  SCH should work,  PCB no.

Lachlan.

**Comment by benjaminaigner** [comment]
I tried it right now, works well with following versions:
KiCAD 4.0.2
Eagle 7.5.0, x64
Debian Testing, x64

Thank you very much for this pretty script!

**Comment by lachlanA** [comment]
Supper,   I'm very pleased !  its working.
There are some problems on the KiCad side with  text rotation,   on the
solder side,
and also on the component side.     But it's in  KiCad import code,  and I
have to submit pact's to the KiCad to fix those.
with luck in a few months I will have them test and ready  to submit.

Lachlan.
