### ISSUE TITLE
wrong comment in ulp

### ISSUE THREAD

**Issue by cscheidl** [lachlanA/eagle-to-kicad#24]
In the Eagle-ulp eagle6xx-sch-to-kicad-sch.ulp, line 2116 there is printf("#P.device.name:....
instead of printf("$P.device.name:...                     or just comment it out by //
That causes Kicad to not open the generated schematic.
Klaus-Michael

**Comment by lachlanA** [comment]
No problems...  
will fix...  slip thou during debuging..

**Comment by lachlanA** [comment]
Fixed,  should be ok now,
thanks for the bug report :)

Lachlan
