### ISSUE TITLE
 test

### ISSUE THREAD

**Issue by ghost** [lachlanA/eagle-to-kicad#30]

**Comment by mecworks** [comment]
@bob808, This bug should be open until the documentation is updated.  The readme still says "Only works correctly for version 4.7 of KiCad, will not work correctly if your using 5.xx version of KiCad to complete the conversion"

**Comment by dandumit** [comment]
long time ago kicad was able to import directly eagle boards. just save your eagle board in new format and this will be imported in kicad pcb

**Comment by bob808** [comment]
Yes, I had a super simple project and I had to repair some stuff to get it working.

**Comment by lachlanA** [comment]
I will run a few checks, and update the doc's,  I thou most people were using the
eagle import in kicad, and using the library conversion script when they  had a large number of
eagle lib's to convert over to kicad, as I see there is no library conversion script in kicad, thou I may have mist it.
Lachlan
