### ISSUE TITLE
Warning: Old KiCad Domain Name

### ISSUE THREAD

**Issue by bboyho** [lachlanA/eagle-to-kicad#32]
@lachlanA , I am not sure how active you are with this project. If you have a some time, you may want to update the KiCad link in the [README.md notes](https://github.com/lachlanA/eagle-to-kicad#readme) by removing the old domain "`-pcb`". The KiCad Development Team released a warning about this recently. Check the links below for details. 

* [https://forum.kicad.info/t/warning-avoid-all-links-to-kicad-pcb-org-use-kicad-org/31521](https://forum.kicad.info/t/warning-avoid-all-links-to-kicad-pcb-org-use-kicad-org/31521)
* [https://hackaday.com/2021/10/20/kicad-team-releases-warning-regarding-domain-name/](https://hackaday.com/2021/10/20/kicad-team-releases-warning-regarding-domain-name/)

**Comment by lachlanA** [comment]
Sorry been away,   looking after my 93 year dad,    and doing PCB stuff.

**Comment by bboyho** [comment]
It's ok. It looks like the link was updated in this commit => https://github.com/lachlanA/eagle-to-kicad/commit/8fc4c76375e1a63a38a992aa6fa774f8d1446b7e . I'll close this comment. =)
