### ISSUE TITLE
eagle6xx-sch-to-kicad-sch.ulp asks wether to apply net list label fix, but ignores choice

### ISSUE THREAD

**Issue by pgroe** [lachlanA/eagle-to-kicad#9]
Line 3228:
`dlgCheckBox("", enableNetListLableFix ); dlgLabel("<nobr><b>Enable Netlist Label Fix</b></nobr>"); dlgSpacing(20); dlgStretch(0);`

is the only real occurance of the variable `enableNetListLableFix`.

It is declared in Line 377: `int enableNetListLableFix = 1;` but that's all.

No evaluation of its value. Just mentioning.

I stumbled across this, as I like to fix the labes by myself.

<EDIT>
@lachlanA : Also mentioning that I really enjoy using the scripts. Great collection - works just fine (with the mentioned downsides of asthetic resulting of this hacks).
</EDIT>

**Comment by pgroe** [comment]
Suggesting patch:
`
--- "eagle6xx-sch-to-kicad-sch-org.ulp"     2016-06-09 19:23:45.046044800 +0200
+++ eagle6xx-sch-to-kicad-sch.ulp       2016-06-09 19:22:52.083951800 +0200
@@ -3001,7 +3001,9 @@
                   write_kicad_wire_segments( SH );
                   write_kicad_bus_segments( SH );
                   write_kicad_dotted_segments( SH );
-                  write_kicad_netNames( SH, current_sheet );
+                  if (enableNetListLableFix) {
+                      write_kicad_netNames( SH, current_sheet );
+                  }
                   printf("$EndSCHEMATC\n");
                 }
               }
`

**Comment by pgroe** [comment]
Suggesting patch:

[eagle6xx-sch-to-kicad-sch.txt](https://github.com/lachlanA/eagle-to-kicad/files/307548/eagle6xx-sch-to-kicad-sch.txt)

**Comment by lachlanA** [comment]
Thanks pgroe,  sorry for the slow replie,
I have been flying from Europe to Australia for last day or so,   so I'm a  bit whacked.
Will look at your input tomorrow..    when my  brain works out what's up and down, and which day it is.. !
Thanks again..

Lachlan

**Comment by lachlanA** [comment]
Thanks pgroe,  sorry for the slow replie,
I have been flying from Europe to Australia for last day or so,   so I'm a  bit whacked.
Will look at your input tomorrow..    when my  brain works out what's up and down, and which day it is.. !
Thanks again..

Lachlan

**Comment by lachlanA** [comment]
I have committed you patch and updated the version and build date to reflect your fix.
thanks for the help,  is nice to have feedback and fix's !
The script's are a really nasty hack,  Nothing I'm proud of,  as you can see by the mess of code.
but Given the limits' of Eagle to KiCad it works most of the time.
Thanks again.
Lachlan

**Comment by pgroe** [comment]
No problem ;) Didn't want to hustle you.
I'm happy I could contribute, but it's only very simple 2 lines of code, whereas you contributes thousands of lines. So thanks to you!

**Comment by lachlanA** [comment]
Any bug fix is good !
No matter how small,    the coded is such a mess,   and I don't get any
feed back,   just stared,  which is nice
but having a email  saying where the problems are..  and works..  is a
1000% better !
Thanks again for the help.

Lachlan.
